version: '3.8'
services:
  streamlit:
    container_name: ffd-streamlit
    build: .
    ports:
      - "${PORT:-8501}:${PORT:-8501}"
    command: >
      sh -c "
      python tools.py init-system &&
      streamlit run home.py --server.port ${PORT:-8502}
      "
    volumes:
      - "${FFD_DATA_PATH}:/app/volumes"
