version: '3.8'
services:
  streamlit:
    container_name: ffd-streamlit
    build: .
    ports:
      - "${PORT:-8501}:${PORT:-8501}"
    command: streamlit run home.py --server.port ${PORT:-8501}
    volumes:
      - "${FFD_SQLITE_PATH}/file_friend.sqlite3:/app/file_friend.sqlite3"
      - "${CREDENTIALS_PATH}/credentials.yaml:/app/credentials.yaml"
